config/routes.rb
Foodtruckies2::Application.routes.draw do
  resources :locations

  get "profiles/show"
  devise_for :truckuser

  devise_scope :truckuser do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
    get '/edit', to: 'devise/registrations#edit', as: :edit
  end

  get '/:profile_id', to: 'profiles#show', as: :profile

  root 'welcome#index'

end

app/models/location.rb
class Location < ActiveRecord::Base

  attr_accessible :city, :state, :zipcode, :address, :id, :latitude, :longitude


  def full_address
    [address, city, state, zipcode].compact.join(', ')
  end

  geocoded_by :full_address
  after_validation :geocode
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @location = Location.find(params[:id])
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])
    @address = Location.find(params[:id]).address
    @city = Location.find(params[:id]).city
    @state = Location.find(params[:id]).state
    @zipcode = Location.find(params[:id]).zipcode
    @latitude = Location.find(params[:id]).latitude
    @longitude = Location.find(params[:id]).longitude
    @full_address = Location.find(params[:id]).full_address

    @hash = Gmaps4rails.build_markers(@location) do |truckuser, marker|
      marker.lat @location.latitude
      marker.lng @location.longitude
    end
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :city, :state, :zipcode, :latitude, :longitude)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/new.html.erb
<style>
    #facebox {

        /* overlay is hidden before loading */
        display:none;

        /* standard decorations */
        width:400px;
        border:10px solid #666;

        /* for modern browsers use semi-transparent color on the border. nice! */
        border:10px solid rgba(82, 82, 82, 0.698);

        /* hot CSS3 features for mozilla and webkit-based browsers (rounded borders) */
        -moz-border-radius:8px;
        -webkit-border-radius:8px;
    }

    #facebox div {
        padding:10px;
        border:1px solid #3B5998;
        background-color:#fff;
        font-family:"lucida grande",tahoma,verdana,arial,sans-serif
    }

    #facebox h2 {
        margin:-11px;
        margin-bottom:0px;
        color:#fff;
        background-color:#6D84B4;
        padding:5px 10px;
        border:1px solid #3B5998;
        font-size:20px;
    }
</style>
<!--[if IE]>
<style type="text/css">
    .facebox {
        background:transparent;
        filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#333333,endColorstr=#333333);
        zoom: 1;
    }
</style>
<![endif]-->

<div id="facebox">
  <div>
    <p>
      Insert your Location
    </p>
    <%= form_for(@location) do |f| %>
        <% if @location.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

              <ul>
                <% @location.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label :address %><br>
          <%= f.text_field :address %>
        </div>
        <div class="field">
          <%= f.label :city %><br>
          <%= f.text_field :city %>
        </div>
        <div class="field">
          <%= f.label :state %><br>
          <%= f.text_field :state %>
        </div>
        <div class="field">
          <%= f.label :zipcode %><br>
          <%= f.text_field :zipcode %>
        </div>
        <div class="field">
          <%= f.label :latitude %><br>
          <%= f.text_field :latitude %>
        </div>
        <div class="field">
          <%= f.label :longitude %><br>
          <%= f.text_field :longitude %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
    <% end %>
    <p style="color:#666">
      To close, click the Close button or hit the ESC key.
    </p>
    <!-- yes/no buttons -->
    <p>
      <button class="close"> Close </button>
    </p>
  </div>
</div>

<script>
    $(document).ready(function() {
        $("#open_now").click(function() {
            $("#facebox").overlay().load();
        });

        // select the overlay element - and "make it an overlay"
        $("#facebox").overlay({

            // custom top position
            top: 260,

            // some mask tweaks suitable for facebox-looking dialogs
            mask: {

                // you might also consider a "transparent" color for the mask
                color: '#fff',

                // load mask a little faster
                loadSpeed: 200,

                // very transparent
                opacity: 0.5
            },

            // disable this for modal dialog-type of overlays
            closeOnClick: false,

            // load it immediately after the construction
            load: true

        });
    });
</script>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
    });
</script>