config/routes.rb
Foodtruckies2::Application.routes.draw do
  resources :locations

  get "profiles/show"
  devise_for :truckuser

  devise_scope :truckuser do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
    get '/edit', to: 'devise/registrations#edit', as: :edit
  end

  get '/:profile_id', to: 'profiles#show', as: :profile

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Food Truckies</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <script src="http://cdn.jquerytools.org/1.2.7/full/jquery.tools.min.js"></script>
</head>
<body>
<%= image_tag("Food_Truckies.png", height: '50px', width: '100px')  %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Food Truckies</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if truckuser_signed_in? %>
          <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
          <li><%= link_to "Log Out", logout_path%></li>
      <% else %>
          <li><%= link_to "Register", register_path %></li>
          <li><%= link_to "Log In", login_path%></li>
      <% end %>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li><a href="<%= profiles_show_path %>">My Profile</a></li>
      <li><a href="/edit">Edit Profile</a></li>
    </ul>
  </section>
</nav>
<div class="container">
  <% flash.each do |type, message| %>
      <div class="alert <%= flash_class type %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= message %>
      </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>